experiment:
  name: "exp_1"
  save_dir: "logs"
  save_interval: 20
  num_threads: 1
  loss_log_dir: "logs/exp_league_1"

env:
  seed: null
  default_reset:
    level: "2"
    banker_pos: 0
    major: "r"
  rules:
    total_cards: 108
    public_cards: 8
    cards_per_player: 25
    win_score: 80
  
  rewards:
    scale_factor: 10.0
    game_over_bonus: 10.0
    score_margin_divisor: 40.0
    aggression_threshold_1: 100
    aggression_bonus_1: 3.0
    aggression_threshold_2: 120
    aggression_bonus_2: 6.0
    win_trick: 0.5
    kill: 0.5
    throw_base: 0.5
    throw_extra: 0.1
    point_unit: 50.0
    banker_punish_mult: 1.5

rl:
  gamma: 0.99
  lambda: 0.95
  clip: 0.2
  lr: 0.0003
  value_coeff: 0.5
  entropy_coeff: 0.04
  entropy_min: 0.001
  entropy_decay: 0.9995
  optimizer_eps: 0.00001
  grad_clip_norm: 0.5
  scheduler:
    step_size: 400
    gamma: 0.9

training:
  device: "cuda"
  replay_buffer_size: 100000
  replay_buffer_episode: 2000
  num_actors: 275
  episodes_per_actor: 1000
  min_sample: 4096
  batch_size: 4096
  mini_batch_size: 1024
  epochs: 10
  actor_start_delay_seconds: 3.0
  actor_start_interval_seconds: 0.1
  ckpt_save_interval: 500
  ckpt_save_path: "checkpoints"
  pretrained_path: null
  model_pool:
    size: 5
    name: "tractor_pool"

opponents:
  heu_bot_prob: 0.05
  neural_bot_prob: 0.60
  better_bot_prob: 0.25
  self_play_prob: 0.10
  default_neural_name: "1935"
  legend_models:
    "1292": "pretrained_models/model_phase1.pt"
    "1935": "pretrained_models/model_phase2.pt"

model:
  hidden_dim: 64
  action_space: [54, 2, 4, 14]

play:
  device: "cpu"
  model_path: "/data/model_plus_global.pt"
  local_input_path: "log_forAI.json"
